version: "3.7"

services:
  # reverse-proxy:
  #   image: nginx:latest
  #   container_name: nginx
  #   # depends_on:
  #   #   - portfolio-client
  #   # - api
  #   # - database
  #   # volumes:
  #   #   - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80/tcp
  #     - 443:443/tcp
  #   # networks:
  #   #   - portfolio-net
  #   restart: always
  portfolio-client:
    image: portfolio-client
    container_name: portfolio-client
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - 8080:3000
    # networks:
    #   - portfolio-net
    stdin_open: true
    restart: on-failure
  # api:
  #   image: api
  #   stdin_open: true
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - xiunet
  #   restart: on-failure
  # database:
  #   image: database
  #   stdin_open: true
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - xiunet
  #   restart: on-failure
# networks:
#   portfolio-net:
#     driver: bridge
# volumes:
#   pg-data:
#     external: true
